/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Configuration for the Anki Chess Opening Trainer Add-On
 */
export interface Config {
	/**
	 * The add-on version that has generated this configuration.
	 */
	version: string;
	/**
	 * The board style
	 */
	board: {
		/**
		 * Whether to use a 3D board.
		 */
		"3D": boolean;
		/**
		 * Style for 2D pieces
		 */
		"2D-pieces":
			| "alpha"
			| "anarcandy"
			| "caliente"
			| "california"
			| "cardinal"
			| "cburnett"
			| "celtic"
			| "chess7"
			| "chessnut"
			| "companion"
			| "cooke"
			| "disguised"
			| "dubrovny"
			| "fantasy"
			| "fresca"
			| "gioco"
			| "governor"
			| "horsey"
			| "icpieces"
			| "kiwen-suwi"
			| "kosal"
			| "leipzig"
			| "letter"
			| "libra"
			| "maestro"
			| "merida"
			| "monarchy"
			| "mpchess"
			| "pirouetti"
			| "pixel"
			| "reillycraig"
			| "riohacha"
			| "shapes"
			| "spatial"
			| "staunty"
			| "tatiana";
	};
}
