/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Configuration for the Anki Chess Opening Trainer Add-On
 */
export interface Config {
	/**
	 * The add-on version that has generated this configuration.
	 */
	version: string;
	/**
	 * The board style
	 */
	board: {
		/**
		 * Whether to use a 3D board.
		 */
		'3D': boolean;
		/**
		 * Style for 2D pieces
		 */
		'2Dpieces':
			| 'alpha'
			| 'anarcandy'
			| 'caliente'
			| 'california'
			| 'cardinal'
			| 'cburnett'
			| 'celtic'
			| 'chess7'
			| 'chessnut'
			| 'companion'
			| 'cooke'
			| 'disguised'
			| 'dubrovny'
			| 'fantasy'
			| 'fresca'
			| 'gioco'
			| 'governor'
			| 'horsey'
			| 'icpieces'
			| 'kiwen-suwi'
			| 'kosal'
			| 'leipzig'
			| 'letter'
			| 'libra'
			| 'maestro'
			| 'merida'
			| 'monarchy'
			| 'mpchess'
			| 'pirouetti'
			| 'pixel'
			| 'reillycraig'
			| 'riohacha'
			| 'shapes'
			| 'spatial'
			| 'staunty'
			| 'tatiana';
		/**
		 * Style for 2D board
		 */
		'2Dboard':
			| 'blue-marble'
			| 'blue2'
			| 'blue3'
			| 'canvas2'
			| 'green-plastic'
			| 'grey'
			| 'horsey'
			| 'leather'
			| 'maple'
			| 'maple2'
			| 'marble'
			| 'metal'
			| 'olive'
			| 'pink-pyramid'
			| 'purple-diag'
			| 'svg/blue'
			| 'svg/brown'
			| 'svg/green'
			| 'svg/ic'
			| 'svg/newspaper'
			| 'svg/purple'
			| 'wood'
			| 'wood2'
			| 'wood3'
			| 'wood4';
		/**
		 * Style for 3D pieces
		 */
		'3Dpieces':
			| 'Basic'
			| 'CubesAndPi'
			| 'Experimental'
			| 'Glass'
			| 'Metal'
			| 'ModernJade'
			| 'ModernWood'
			| 'RedVBlue'
			| 'Staunton'
			| 'Trimmed'
			| 'Wood';
		/**
		 * Style for 3D board
		 */
		'3Dboard':
			| 'Black-White-Aluminium'
			| 'Brushed-Aluminium'
			| 'China-Blue'
			| 'China-Green'
			| 'China-Grey'
			| 'China-Scarlet'
			| 'China-Yellow'
			| 'Classic-Blue'
			| 'Glass'
			| 'Gold-Silver'
			| 'Green-Glass'
			| 'Jade'
			| 'Light-Wood'
			| 'Marble'
			| 'Power-Coated'
			| 'Purple-Black'
			| 'Rosewood'
			| 'Wax'
			| 'Wood-Glass'
			| 'Woodi';
		/**
		 * Orientation of the board
		 */
		orientation: 'Automatic' | 'White' | 'Black';
		/**
		 * Let a clock run while you are finding the answer(s)
		 */
		displayClock: boolean;
	};
	/**
	 * Modify the studying process.
	 */
	studying?: {
		/**
		 * Show an empty move entry for each expected move.
		 */
		showNumberOfAnswers: boolean;
		/**
		 * Automatically turn the card, when all moves have been entered.
		 */
		autoTurnCard: boolean;
	};
}
