[tool.yapf]
based_on_style = "pep8"

# See https://lea.verou.me/blog/2012/01/why-tabs-are-clearly-superior/.
use_tabs = "True"

i18n_comment = "# TRANSLATORS:"
i18n_function_call = [ "_", "ngettext" ]

[tool.yapfignore]
ignore_patterns = [
	"src/forms/**/*",
	"src/vendor/**/*"
]

[tool.isort]
skip = [
	"src/forms/**/*",
	"src/vendor/**/*"
]