# generated by datamodel-codegen:
#   filename:  config.schema.json
#   timestamp: 2024-06-11T20:25:47+00:00

from __future__ import annotations

from typing import Dict, List, Optional

from typing_extensions import Literal, TypedDict


class Decks(TypedDict):
	white: Optional[int]
	black: Optional[int]


class Imports(TypedDict):
	colour: Literal['black', 'white']
	files: List[str]


class Config(TypedDict):
	version: str
	colour: Literal['white', 'black']
	decks: Decks
	imports: Dict[str, Imports]
	notetype: Optional[int]
